### ISSUE TITLE
Metadata migration Retrieve All 

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/SublimeApex#72]
Retrieve All pull all components into the src folder rather than metadata/src folder.

**Comment by xjsender** [comment]
@Shababsoft , yes, it is now since release 2.6.0, so what's the problem here?

**Comment by Shababsoft** [comment]
There is no problem, I did not know. Is it possible you can provide option to download full metadata to metadata/src folder or src. Because I want only normal components (classes, VF, components, trigger, staticresource) in src folder. I use metadata migration for backup and git push.
