### ISSUE TITLE
Error When Executing Anonymous 

### ISSUE THREAD

**Issue by lqcys** [xjsender/SublimeApex#75]
When add comments in Anonymous Execution, the plug-in cannot operation properly.
![errors](https://cloud.githubusercontent.com/assets/3202603/5758860/025aaf9e-9d04-11e4-97f6-d74f762c269d.jpg)

**Comment by xjsender** [comment]
@lqcys , it's a potential bug of [xmlformatter](https://pypi.python.org/pypi/xmlformatter/) and will be fixed in next release.
